# Generated by Django 3.0.7 on 2020-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahjong_Uma_Oka_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='taro', max_length=100)),
                ('uma', models.CharField(choices=[('なし', 'なし'), ('5-10', '5-10'), ('5-15', '5-15'), ('10-20', '10-20'), ('10-30', '10-30'), ('20-30', '20-30')], default='なし', max_length=50)),
                ('oka', models.IntegerField(default=25000)),
                ('uma_oka_benefit_of_2nd_player', models.IntegerField(blank=True, default=0, null=True)),
                ('uma_oka_benefit_of_3rd_player', models.IntegerField(blank=True, default=0, null=True)),
                ('uma_oka_benefit_of_4th_player', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MahjongPlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='taro', max_length=100)),
                ('player1', models.CharField(default='player1', max_length=10)),
                ('player2', models.CharField(default='player2', max_length=10)),
                ('player3', models.CharField(default='player3', max_length=10)),
                ('player4', models.CharField(default='player4', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MahjongRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='taro', max_length=100)),
                ('rank1', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], default='1st', max_length=50)),
                ('rank2', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], default='2nd', max_length=50)),
                ('rank3', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], default='3rd', max_length=50)),
                ('rank4', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], default='4th', max_length=50)),
                ('score1', models.IntegerField(default=25000)),
                ('score2', models.IntegerField(default=25000)),
                ('score3', models.IntegerField(default=25000)),
                ('score4', models.IntegerField(default=25000)),
                ('calculatedscore1', models.IntegerField(blank=True, default=0, null=True)),
                ('calculatedscore2', models.IntegerField(blank=True, default=0, null=True)),
                ('calculatedscore3', models.IntegerField(blank=True, default=0, null=True)),
                ('calculatedscore4', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
